name: CD to Kubernetes

on:
  push:
    branches:
      - main
      - feature/CD-config

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        cd parking-api/
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        cd parking-api/
        kubectl set image deployment/my-app-deployment my-app-container=${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
